# Standards: 1.2
---
- name: Restart node-exporter
  systemd:
    name: node-exporter
    state: restarted
    daemon_reload: yes

- name: Restart blackbox-exporter
  systemd:
    name: blackbox-exporter
    state: restarted
    daemon_reload: yes

...
